server:
  port: 8899
  servlet:
    context-path: /api
    encoding:
      enabled: true
      force: true
      charset: UTF-8

spring:
  ai:
    dashscope:
      api-key: ${AI_DASHSCOPE_API_KEY}
  application:
    name: chat