server:
  port: 8084
  servlet:
    context-path: /so
    encoding:
      enabled: true
      force: true
      charset: UTF-8

spring:
  application:
    name: stream-output
  thymeleaf:
    prefix: classpath:/templates/
    cache: false
    encoding: UTF-8
    mode: HTML